// Modal
export const MOSTRAR_OCULTAR_MODAL_MENSAJE = 'MOSTRAR_OCULTAR_MODAL_MENSAJE';

// Mensaje
export const AGREGAR_MENSAJE = 'AGREGAR_MENSAJE';
export const ELIMINAR_MENSAJE = 'ELIMINAR_MENSAJE';

// Formulario
export const VALIDACION_FORMULARIO = 'VALIDACION_FORMULARIO';
